import { randomBytes } from "crypto";
import { db } from "@/db";
import { shareLinks } from "@/db/schema";
import { and, eq, isNull } from "drizzle-orm";

/**
 * Client portal links use an opaque, unguessable random token stored in
 * `share_links` (not a signed JWT) so a link can be instantly revoked or
 * regenerated by deleting/rotating the DB row — no token blacklist needed.
 */
export function generateToken(): string {
  return randomBytes(24).toString("base64url");
}

export async function getOrCreateShareLink(engagementId: string, kind: "live" | "report") {
  const [existing] = await db
    .select()
    .from(shareLinks)
    .where(
      and(
        eq(shareLinks.engagementId, engagementId),
        eq(shareLinks.kind, kind),
        isNull(shareLinks.revokedAt)
      )
    )
    .limit(1);

  if (existing) return existing;

  const [created] = await db
    .insert(shareLinks)
    .values({ engagementId, kind, token: generateToken() })
    .onConflictDoUpdate({
      target: [shareLinks.engagementId, shareLinks.kind],
      set: { token: generateToken(), revokedAt: null },
    })
    .returning();

  return created;
}

export async function regenerateShareLink(engagementId: string, kind: "live" | "report") {
  const [updated] = await db
    .insert(shareLinks)
    .values({ engagementId, kind, token: generateToken() })
    .onConflictDoUpdate({
      target: [shareLinks.engagementId, shareLinks.kind],
      set: { token: generateToken(), revokedAt: null },
    })
    .returning();
  return updated;
}

export async function revokeShareLink(engagementId: string, kind: "live" | "report") {
  await db
    .update(shareLinks)
    .set({ revokedAt: new Date() })
    .where(and(eq(shareLinks.engagementId, engagementId), eq(shareLinks.kind, kind)));
}

export async function resolveShareToken(token: string, kind: "live" | "report") {
  const [link] = await db
    .select()
    .from(shareLinks)
    .where(and(eq(shareLinks.token, token), eq(shareLinks.kind, kind), isNull(shareLinks.revokedAt)))
    .limit(1);
  return link ?? null;
}
