import { randomBytes } from "crypto";
import { db } from "@/db";
import { shareLinks } from "@/db/schema";
import { and, eq, isNull } from "drizzle-orm";

/**
 * Client portal links use an opaque, unguessable random token stored in
 * `share_links` (not a signed JWT) so a link can be instantly revoked or
 * regenerated by deleting/rotating the DB row — no token blacklist needed.
 */
export function generateToken(): string {
  return randomBytes(24).toString("base64url");
}

/**
 * Returns the engagement's current share link for `kind`, creating one only
 * if none exists yet. A REVOKED link is returned as-is (with revokedAt set)
 * rather than silently resurrected — callers must check `revokedAt` and use
 * regenerateShareLink() to explicitly issue a new one. This function is
 * called on every Dashboard/Report page render, so it must never itself
 * un-revoke a link or "Revoke" would never stick.
 */
export async function getOrCreateShareLink(engagementId: string, kind: "live" | "report") {
  const [existing] = await db
    .select()
    .from(shareLinks)
    .where(and(eq(shareLinks.engagementId, engagementId), eq(shareLinks.kind, kind)))
    .limit(1);

  if (existing) return existing;

  const [created] = await db
    .insert(shareLinks)
    .values({ engagementId, kind, token: generateToken() })
    .onConflictDoNothing({ target: [shareLinks.engagementId, shareLinks.kind] })
    .returning();

  if (created) return created;

  // Lost an insert race — re-select the row the other request created.
  const [row] = await db
    .select()
    .from(shareLinks)
    .where(and(eq(shareLinks.engagementId, engagementId), eq(shareLinks.kind, kind)))
    .limit(1);
  return row;
}

export async function regenerateShareLink(engagementId: string, kind: "live" | "report") {
  const [updated] = await db
    .insert(shareLinks)
    .values({ engagementId, kind, token: generateToken() })
    .onConflictDoUpdate({
      target: [shareLinks.engagementId, shareLinks.kind],
      set: { token: generateToken(), revokedAt: null },
    })
    .returning();
  return updated;
}

export async function revokeShareLink(engagementId: string, kind: "live" | "report") {
  await db
    .update(shareLinks)
    .set({ revokedAt: new Date() })
    .where(and(eq(shareLinks.engagementId, engagementId), eq(shareLinks.kind, kind)));
}

export async function resolveShareToken(token: string, kind: "live" | "report") {
  const [link] = await db
    .select()
    .from(shareLinks)
    .where(and(eq(shareLinks.token, token), eq(shareLinks.kind, kind), isNull(shareLinks.revokedAt)))
    .limit(1);
  return link ?? null;
}
